### ISSUE TITLE
Unique Like Button

### ISSUE THREAD

**Issue by Nazirovich** [candelibas/instaclone#4]
I'm new using ionic and i'm using your code to develop a personal application.

How can i make the like button unique.
I want only the clicked heart to change and not all the hearts in the page like it is now?

 <button clear ion-button icon-only (click)="likeButton()" class="like-btn">
          <ion-icon no-padding [name]="like_btn.icon_name" color="{{ like_btn.color }}" class="icon-space"></ion-icon></button>

---------------------

likeButton() {
    if(this.like_btn.icon_name === 'heart-outline') {
      this.like_btn.icon_name = 'heart';
      this.like_btn.color = 'danger';
      // Do some API job in here for real!
    }
    else {
      this.like_btn.icon_name = 'heart-outline';
      this.like_btn.color = 'black';
    }
  }

Thank you.

**Comment by candelibas** [comment]
Hi @Nazirovich,

You can create another function & style just like likeButton() and CSS definitions and use it however you like.
