### ISSUE TITLE
Future improvements with backend

### ISSUE THREAD

**Issue by omurbekjk** [candelibas/instaclone#6]
Hi @candelibas, this repo looks good, what about adding backend for this repo such as `Firebase`?

**Comment by candelibas** [comment]
Hey @omurbekjk,

I'm glad that you liked it. Unfortunately, I'm not available to add any type of backend. Hope someone will add or you can feel free to contribute.

**Comment by candelibas** [comment]
Hey @omurbekjk,

I'm glad that you liked it. Unfortunately, I'm not available to add any type of backend. Hope someone will add or feel free to contribute.
